spring:
  application:
    name: notification

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: orner.queue
  routing:
    name: order.tracking

server:
  port: 8084